#Persistent working directory to use
working_dir: /workspaces/elliott-working-dir

#Git URL or File Path to build data
data_path: https://github.com/openshift/ocp-build-data.git

#Sub-group directory or branch to pull build data
# group:
